version: '3.6'
services:
  telegraf:
    image: mihudec/telegraf-snmp-net
    container_name: telegraf
    restart: on-failure
    volumes:
   # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - telegraf_data:/var/lib/telegraf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb
    #platform: linux/amd64
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE="${DOCKER_INFLUXDB_INIT_MODE}"
      - DOCKER_INFLUXDB_INIT_USERNAME="${DOCKER_INFLUXDB_INIT_USERNAME}"
      - DOCKER_INFLUXDB_INIT_PASSWORD="${DOCKER_INFLUXDB_INIT_PASSWORD}"
      - DOCKER_INFLUXDB_INIT_ORG="${DOCKER_INFLUXDB_INIT_ORG}"
      - DOCKER_INFLUXDB_INIT_BUCKET="${DOCKER_INFLUXDB_INIT_BUCKET}"
      #- DOCKER_INFLUXDB_INIT_RETENTION=
      #- DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER="${USER}"
      - GF_SECURITY_ADMIN_PASSWORD="${AUTH}"
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
  telegraf_data: {}
